version: '3.8'
services:

  bridge-api:
    build:
      context: bridge-api
      args:
        JAR: ./target/*.jar
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      MOCK_SERVER_URL: http://wiremock:8080
    depends_on:
      - wiremock

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files

