spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://mock-server-db:5432/mockdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update