name: bridge-api.yml
on:
  pull_request:
    branches:
      - main
    paths:
      - 'bridge-api/**'
      - '.github/workflows/bridge-api.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Build & Test bridge-api
        run: |
          ./mvnw -B package --file pom.xml -pl bridge-api/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bridge-api-artifacts
          path: |
            bridge-api/target/*.jar
            bridge-api/Dockerfile