name: workflow.yml
on:
  pull_request:
    branches:
      - main
    paths:
      - 'bridge-api/**'
      - 'mock-server/**'
      - 'pom.xml'
      - '.mvn/**'
      - 'mvnw'
      - 'mvnw.cmd'
jobs:
  set-up:
    runs-on: ubuntu-latest
    outputs:
      changed-modules: ${{ steps.detect.outputs.changed-modules }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Detect changed modules
        id: detect
        run: |
          echo "changed=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} \
            | awk -F/ '{print $1}' \
            | grep -E 'bridge-api|mock-server' \
            | sort \
            | uniq \
            | paste -sd ",")" >> $GITHUB_OUTPUT

  build-bridge-api:
    if: contains(needs.set-up.outputs.changed-modules, 'bridge-api') || needs.set-up.outputs.changed-modules == ''
    needs: set-up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      - name: Build and test bridge-api
        run: |
          ./mvnw --batch-mode -pl bridge-api clean verify

  build-mock-server:
    if: contains(needs.set-up.outputs.changed-modules, 'mock-server') || needs.set-up.outputs.changed-modules == ''
    needs: set-up
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mockdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      - name: Build and test mock-server
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mockdb
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: example
        run: |
          ./mvnw --batch-mode -pl mock-server clean verify
